// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDirectory(arg1:string,arg2:string):Promise<string>;
export function CreateFile(arg1:string,arg2:string):Promise<string>;
export function CreateProject(arg1:string,arg2:string):Promise<string>;
export function GetHomeDir():Promise<string>;
export function OpenFolder():Promise<string>;
export function QuitApp():Promise<void>;
export function ReadDirectory(arg1:string):Promise<Array<main.FileNode>>;
