// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentProject(arg1) {
  return window['go']['main']['App']['AddRecentProject'](arg1);
}

export function ClearRecentProjects() {
  return window['go']['main']['App']['ClearRecentProjects']();
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}
