// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Compile() {
  return window['go']['main']['App']['Compile']();
}

export function CreateChapter(arg1, arg2) {
  return window['go']['main']['App']['CreateChapter'](arg1, arg2);
}

export function CreateWorkspace(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateWorkspace'](arg1, arg2, arg3, arg4);
}

export function DeleteChapter(arg1) {
  return window['go']['main']['App']['DeleteChapter'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function GetDocumentOverrides(arg1) {
  return window['go']['main']['App']['GetDocumentOverrides'](arg1);
}

export function GetProject() {
  return window['go']['main']['App']['GetProject']();
}

export function ImportAttachmentPDF() {
  return window['go']['main']['App']['ImportAttachmentPDF']();
}

export function ImportImage() {
  return window['go']['main']['App']['ImportImage']();
}

export function ListAvailablePlugins() {
  return window['go']['main']['App']['ListAvailablePlugins']();
}

export function ListChapters() {
  return window['go']['main']['App']['ListChapters']();
}

export function ListStyles() {
  return window['go']['main']['App']['ListStyles']();
}

export function ListTargetPresets() {
  return window['go']['main']['App']['ListTargetPresets']();
}

export function ListTargets() {
  return window['go']['main']['App']['ListTargets']();
}

export function LoadChapter(arg1) {
  return window['go']['main']['App']['LoadChapter'](arg1);
}

export function OpenWorkspace(arg1) {
  return window['go']['main']['App']['OpenWorkspace'](arg1);
}

export function OpenWorkspaceDialog() {
  return window['go']['main']['App']['OpenWorkspaceDialog']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function ReorderChapters(arg1) {
  return window['go']['main']['App']['ReorderChapters'](arg1);
}

export function SaveChapter(arg1, arg2) {
  return window['go']['main']['App']['SaveChapter'](arg1, arg2);
}

export function SaveDocumentOverrides(arg1, arg2) {
  return window['go']['main']['App']['SaveDocumentOverrides'](arg1, arg2);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveStyles(arg1) {
  return window['go']['main']['App']['SaveStyles'](arg1);
}

export function SaveTarget(arg1) {
  return window['go']['main']['App']['SaveTarget'](arg1);
}

export function SetActiveTarget(arg1) {
  return window['go']['main']['App']['SetActiveTarget'](arg1);
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function Validate() {
  return window['go']['main']['App']['Validate']();
}
