// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDirectory(arg1, arg2) {
  return window['go']['main']['App']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2) {
  return window['go']['main']['App']['CreateFile'](arg1, arg2);
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function ReadDirectory(arg1) {
  return window['go']['main']['App']['ReadDirectory'](arg1);
}
