// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface FileNode {
  name: string;
  path: string;
  isDir: boolean;
}

export function OpenFolder(): Promise<string>;
export function QuitApp(): Promise<void>;
export function ReadDirectory(arg1: string): Promise<FileNode[]>;
